<a href="https://colab.research.google.com/github/Kacper-Dz/APRdataPL9-KD/blob/main/Statystyka_zajecia1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
wektor = np.array([1, 2, 3])
wektor

array([1, 2, 3])

In [4]:
lista1 = ([4, 5, 6])
wektor=np.array(lista1)
wektor

array([4, 5, 6])

In [6]:
wektor_kolumnowy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
wektor_kolumnowy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
macierz = np.array([[1, 2, 3], [4, 5, 6]]) 
macierz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(5, 15, 2)

array([ 5,  7,  9, 11, 13])

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Podsumowanie
W jaki sposób tworzymy wektory:
* np.array() - tworzymy wektro według podanych elementów
* np.arrange() - tworzymy wektor według zadeklarowanej funkcji
* np.linspace - wiemy ile chcemy elementów, niekonieczniej jakie mają mieć wartości, definiujemy zakres wartości i ilość elementów.

In [19]:
macierz = np.array([
    np.linspace(0, 333, 5),
    np.linspace(467, 874, 5),
    np.linspace(259, 678, 5)
])

macierz

array([[  0.  ,  83.25, 166.5 , 249.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [259.  , 363.75, 468.5 , 573.25, 678.  ]])

In [20]:
macierz.shape  #".shape", czyli atrybut "shape" mówia nam o tym jakie są wymairy obiektu macierz, najpierw liczba wierszy, potem liczba kolumn

(3, 5)

In [24]:
wektor.shape  #".shape", czyli atrybut "shape" mówia nam o tym jakie są wymairy obiektu wektro

(3,)

In [21]:
macierz.size  # rozmiar, czyli iloczyn wymiarów

15

In [22]:
macierz.ndim  # liczba wymiarów

2

In [23]:
wektor.ndim

1

In [25]:
# Tenosr 0D
skalar = [1]
skalar

[1]

In [26]:
# Tensor 1d
wektor = [1, 2, 3]
wektor

[1, 2, 3]

In [28]:
# Tensor 2D
macierz = np.array([[1, 2, 3], [4, 5, 6]])
macierz

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
macierz = np.array([
    np.linspace(0, 333, 5),
    np.linspace(467, 874, 5),
    np.linspace(259, 678, 5)
])

macierz

array([[  0.  ,  83.25, 166.5 , 249.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [259.  , 363.75, 468.5 , 573.25, 678.  ]])

In [31]:
macierz.shape

(3, 5)

In [32]:
macierz [1][1]  # Numeracja od 0

568.75

In [33]:
macierz[1, 1]  # Numeracja od 0

568.75

In [34]:
macierz.shape # najpier wiersze, potem kolumny

(3, 5)

In [36]:
macierz[0]

array([  0.  ,  83.25, 166.5 , 249.75, 333.  ])

In [37]:
macierz [0, :]  # wyświetlamy wiersz nr 0

array([  0.  ,  83.25, 166.5 , 249.75, 333.  ])

In [38]:
macierz [:, 0] # Wyświetlamy kolumnę nr 0, nie działa tutaj zapis [][0]

array([  0., 467., 259.])

In [40]:
macierz [:, 2:] # Zwrot wszytskich wierszy i kolumn od 1 

array([[166.5 , 249.75, 333.  ],
       [670.5 , 772.25, 874.  ],
       [468.5 , 573.25, 678.  ]])

In [ ]:
# dostajemy elementy oznaczone przez x
# [o o x x x]
# [o o x x x]
# [o o x x x]

In [41]:
np.random.random()

0.6302509785278042

In [42]:
np.random.random(10)

array([0.90306297, 0.56771938, 0.59931108, 0.28055586, 0.40228817,
       0.8345941 , 0.72067202, 0.0564755 , 0.63694659, 0.64015279])

In [44]:
np.random.random(10).ndim

1

In [ ]:
np.random.normal() # Losowa liczba z rozkladu normalnego      https://pl.wikipedia.org/wiki/Rozk%C5%82ad_normalny
np.random.uniform() # Losowa liczba z rozkładu jednostajnego  https://pl.wikipedia.org/wiki/Rozk%C5%82ad_jednostajny_ci%C4%85g%C5%82y

In [45]:
# Opcja dla liczb całkowitych, z powtórzeniami
np. random.randint(0, 100, size=10)

array([79, 45, 26, 74, 40, 45, 62, 29, 72, 32])

In [46]:
wektor = np.array([20, 17, 67, 456, 100, 6, 12.5])
wektor

array([ 20. ,  17. ,  67. , 456. , 100. ,   6. ,  12.5])

In [47]:
wektor_wieksze_od_99 = np.where(wektor >99)
wektor_wieksze_od_99

(array([3, 4]),)

In [48]:
wektor[wektor_wieksze_od_99] # Stosujemy wektor jako filtr do wektora

array([456., 100.])

In [59]:
# Zadanie 1.
# Stwórz numpy array z wartosciami od 1 do 9, wyświetl a następnie odwróć tę
# tablicę (pierwszy element zostaje ostatnim, itd.)

zadanie1 = np.arange(1,10)
print(zadanie1)
zadanie1 = np.flip(zadanie1)
print(zadanie1)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [60]:
zadanie1[-1:]

array([1])

In [61]:
zadanie1 [::-1] # https://stackoverflow.com/questions/6771428/most-efficient-way-to-reverse-a-numpy-array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Zadanie 2.
# Stwórz następujący numpy array [1, 23, 4, 31, 1, 1, 4, 23, 4, 1],
# a następnie wypisz wszytskie unikalne (nie powtarzające sie) elementy

zadanie2 = [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]
zadanie2un = np.array(zadanie2)
np.unique(zadanie2un)

array([ 1,  4, 23, 31])

## Działanie na macierzach

In [63]:
matrix_a = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8],
])

matrix_b = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30],
])


In [64]:
print(matrix_a)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [65]:
print(matrix_b)

[[10 10 10]
 [20 20 20]
 [30 30 30]]


In [66]:
np.add(matrix_a, matrix_b)

array([[11, 12, 13],
       [23, 24, 25],
       [36, 37, 38]])

In [68]:
np.subtract(matrix_a, matrix_b)

array([[ -9,  -8,  -7],
       [-17, -16, -15],
       [-24, -23, -22]])

In [69]:
matrix_a + matrix_b

array([[11, 12, 13],
       [23, 24, 25],
       [36, 37, 38]])

In [70]:
matrix_b - matrix_a

array([[ 9,  8,  7],
       [17, 16, 15],
       [24, 23, 22]])

In [71]:
matrix_a * matrix_b

array([[ 10,  20,  30],
       [ 60,  80, 100],
       [180, 210, 240]])

In [72]:
matrix_a * 2

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [12, 14, 16]])

In [73]:
matrix_a * np.array([10, 20, 30])

array([[ 10,  40,  90],
       [ 30,  80, 150],
       [ 60, 140, 240]])

In [74]:
# transpozycja macierzy
matrix_a.T
# Jeśli w macierzy "i" to wiersza a "j" to kolumny, to element ma indeks X_(i, j),
# Odwrócenie macierzy polega na zamianie "i" oraz "j" miejscami
# Transpozycja zachowuje przekątną

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

In [76]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
# Zadanie 3.
# Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10.

zadanie3 = np.arange(2, 11, 1)
zadanie3 = zadanie3.reshape(3, 3)
print(zadanie3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [88]:
# Zadanie 4.
# Stwórz tablicę z sześcioma losowymi wartościami z przedziału od 10 do 30.

zadanie4 = np.random.randint(10, 30, size=6)
zadanie4 = zadanie4.reshape(2, 3)
print(zadanie4)

[[27 16 23]
 [20 17 24]]


In [99]:
# Zadanie 5.
# Spośród tablicy wartości: [23, 45, 112, 150, 43, 254, 95, 8] wyfiltruj te,
# które są większe od 100

zadanie5 = np.array([23, 45, 112, 150, 43, 254, 95, 8])
zadanie5[np.where(zadanie5 > 100)]


array([112, 150, 254])

In [107]:
# Zadanie 6.
# Stwórz poniższą macierz 4x4, a następnie:
# (a) wyświetl element z drugiego wiersza i trzeciej kolumny,
# (b) oblicz jej ślad (sumę elementów na głównej przekątnej), 
# (c) znajdź element największy i najmniejszy.

matrix6 = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

print(f"2 wiersz i 3 kolumnama to: {matrix6[1, 2]}")
print(f"Ślad macierzy = {matrix6.diagonal().sum()}")
print(f"Min = {matrix6.min()}")
print(f"Max = {matrix6.max()}")


2 wiersz i 3 kolumnama to: 3
Ślad macierzy = 35
Min = 0
Max = 32
